### ISSUE TITLE
How to use MaterialdDatePicker.DatePickerDialog().Show() with FragmentTransactions

### ISSUE THREAD

**Issue by CDrosos** [Plac3hold3r/PH.Wdullaer.Materialdatetimepicker#1]
Hello, thanks for this package.
Im trying to understand how to use your code. In your App example you use viewpager and you create an adapter for this. But what if we don't want to use a ViewPager and we just want to use a fragment to display the dialog? For example on my Activity im showing the fragment this way:

```
            FragmentTransaction fragmentTx = FragmentManager.BeginTransaction();
            ChooseDateTimeFragment aDifferentDetailsFrag = new ChooseDateTimeFragment();
            fragmentTx.Add(Resource.Id.ChooseDateTimeFragment, aDifferentDetailsFrag);
            fragmentTx.Commit();
```

What then i have to use on the MaterialdDatePicker.DatePickerDialog().Show() function? i dont have an adapter to use FragmentManager and i cant access FragmentTransaction of the Activity from the fragment i think, im a little confused.
Thanks @Plac3hold3r

**Comment by Plac3hold3r** [comment]
Hi @CDrosos , you can definitely make use of `MaterialdDatePicker` without requiring an Adapter or a view pager. The `FragmentManager` that gets past to the `Show` can be found as a get only property on your `Activity` or `Fragment`.

```C#
new DatePickerDialog().Show(FragmentManager, "Datepickerdialog");
```
Let me know if I'm maybe miss understanding what the issue is?

**Comment by CDrosos** [comment]
oh great, i can do this:

`new DatePickerDialog().Show(FragmentManager, "Datepickerdialog");`

without having an adapter for the fragmentmanager. so this means that in your example you was overriding the default fragment manager in order to have a more automatically way to add many fragments?

I guess i can also do this:
```
FragmentTransaction fragmentTx = FragmentManager.BeginTransaction();
            dpd.Show(fragmentTx , "Datepickerdialog");
```
From a fragment and the fragment transaction will be as it was initiated from the Activity? I thought it will be harder than that.

**Comment by Plac3hold3r** [comment]
You should be able to use the `FragmentManager` directly via the show, no need for the `FragmentTransaction`.

**Comment by CDrosos** [comment]
super, thanks

**Comment by CDrosos** [comment]
may i ask something else?

if i try to use using Fragment = Android.Support.V4.App.Fragment;
i get an error that i can't convert Android.App.Fragment to Android.Support.V4.App.Fragment; what if someone really needs to use Android.Support.V4.App.Fragment for fragments?

thanks

**Comment by Plac3hold3r** [comment]
The binding for this library is based on wdullaer MaterialDateTimePicker which uses Android native fragments. There is a note on their [FAQ](https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment) which relates to your question. In short, they currently make use of Android's native fragments as opposed to the support library versions. You can make use of both patterns in the same app.

**Comment by Plac3hold3r** [comment]
@CDrosos where you able to resolve your issue?

**Comment by CDrosos** [comment]
yes, thanks for the help
