### ISSUE TITLE
Version Upgrade

### ISSUE THREAD

**Issue by manikandan-selvanathan** [Plac3hold3r/PH.Wdullaer.Materialdatetimepicker#4]
Please upgrade to latest 4.1.2 version.

**Comment by Plac3hold3r** [comment]
Hi @manikandansai , unfortunately I believe I have to wait for Xamarin to bring stable support for AndroidX packages. Version 4+ of Material DateTime Picker has a dependency on AndroidX which I can not map via a NuGet Package.
Once Xamarin releases a preview of AndroidX package to NuGet I can update this binding project to match.

**Comment by cristiandaulisio** [comment]
any news on upgrade? I saw other wrappers that are at v4, any chance to update this one?

**Comment by Plac3hold3r** [comment]
Hey, @Atomico001, still waiting on the future release of AndroidX. You can check out the [Xamarin- .NET Community Standup - June 6th 2019 - AndroidX with Jon Dick](https://channel9.msdn.com/Shows/NET-Community-Standups/Xamarin-NET-Community-Standup-June-6th-2019-AndroidX-with-Jon-Dick) where they are discussing the latest developments around AndroidX. From the sounds of things, they are aligning with a Visual Studio tooling update before releasing.

**Comment by Plac3hold3r** [comment]
@manikandansai  @Atomico001 you can now find `v2.421.0-beta.1` which has support for version `4.2.1` of Wdullaer Material Datetime Picker and Android X packages.
