### ISSUE TITLE
How i can use TimePickerDialog().Show() without fragments?

### ISSUE THREAD

**Issue by CDrosos** [Plac3hold3r/PH.Wdullaer.Materialdatetimepicker#6]
i'm trying to use this library but i see that always needs as a parameter a FragmentManager, im not using fragments, how i can show then a timepickerDialog?

**Comment by Plac3hold3r** [comment]
Hi @CDrosos , while `TimePickerDialog` is a fragment you don't have to launch the dialog from a fragment. If your application is only using activities that is fine.  You must just make use of a [`FragmentActivity`](https://developer.android.com/reference/androidx/fragment/app/FragmentActivity).
